FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache curl

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

RUN npm run prisma:generate

COPY . .

ENV NODE_ENV=development

EXPOSE 3001

CMD ["sh", "-c", "npx prisma migrate dev --name init && npm run dev"]
